import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getUserId } from "@/lib/session";
import { getUserById } from "@/lib/db/queries";
import Navbar from "@/components/navbar";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tutorly",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = await getUserId();
  let user = null;
  if (userId) {
    user = await getUserById(userId);
  }

  return (
      <section
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar username={user?.name || "Guest"} saldo={user?.saldo || 0}>
          <section>{children}</section>
        </Navbar>
      </section>
  );
}
